version: 0.0
os: linux
files:
  - source: /appA
    destination: /
hooks:
  ApplicationStop:
    - location: applicationstop.sh
      timeout: 15
      runas: root
  BeforeInstall:
    - location: beforeinstall.sh
      timeout: 15
      runas: root
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 15
      runas: root
